// import structureForm from "../../structure/structureForm";
// import api from "../../api";
// import moment from "moment";
export default {
  actualDataGrid: [
    
  ],
  settingsFilter: {},
  filledForms: {},
  allShips: [],
  asyncCargoTypes:[],
  backendForms: {
    EnterSeePort: ["createDate", "placeNsr", "placeNsrLon", "placeNsrLat", "placeNsrDate", "shipId"],
    EnterDispAqua: [
      "enterDate",
      "enterPlace",
      "enterLon",
      "enterLat",
      "course",
      "speed",
      "exitDate",
      "exitPlace",
      "exitLon",
      "exitLat",
      "exitType",
      "createDate",
      "shipId",
    ],
    ExitDispAqua: ["createDate", "course", "speed", "exitDate", "exitPlace", "exitLon", "exitLat", "shipId"],
    CreateDispAqua: [
      "createDate",
      "departurePlace",
      "departureLon",
      "departureLat",
      "departureDate",
      "destinationPlace",
      "destinationLon",
      "destinationLat",
      "destinationDate",
      "draught",
      "fuelLight",
      "fuelHeavy",
      "fuelSpg",
      "fuelDays",
      "waterDays",
      "provisionDays",
      "crew",
      "passangers",
      "damage",
      "enterPlace",
      "enterLon",
      "enterLat",
      "enterDate",
      "shipId",
      "ctFk",
      "hcFk",
      "towedShips"
    ],
    ExitSeePort: [
      "createDate",
      "departurePlace",
      "departureLon",
      "departureLat",
      "departureDate",
      "destinationPlace",
      "destinationLon",
      "destinationLat",
      "destinationDate",
      "draught",
      "fuelLight",
      "fuelHeavy",
      "fuelSpg",
      "fuelDays",
      "waterDays",
      "provisionDays",
      "crew",
      "passangers",
      "damage",
      "exitPlace",
      "exitLon",
      "exitLat",
      "exitDate",
      "exitType",
      "shipId",
    ],
    SwimDispAqua:[
        "createDate",
        "placeNsrLon",
        "placeNsrLat",
        "exitType",
        "exitDate",
        "exitPlace",
        "exitLon",
        "exitLat",
        "course",
        "speed",
        "fuelLight",
        "fuelHeavy",
        "fuelSpg",
        "water",
        "incidents",
        "shipFault",
        "emergency",
        "atmTemperature" ,
        "atmPressure" ,
        "windDir" ,
        "windSpeed" ,
        "visibility" ,
        "weatherEvents",
        "waterTemperature" ,
        "iceCompression" ,
        "iceRidge" ,
        "iceDestruction" ,
        "icing",
        "iceEvents",
        "equipmentFault",
        "shipId" ,
        "ct",
        "ca",
        "cb",
        "cc",
        "sa" ,
        "sb" ,
        "sc" 
    ]
  },
  ports:[],
  allPorts:[],
  nameMarker : ""
};
