import headerButtons from "../../header/headerButtons";

export default {
  structureType: "Form",
  components: [
    {
      id: 100, 
      parentId: 0,
      visible: true,
      componentName: "CreateDispAquaHeader",
      component: "EPCSFormHeader",
      props: { title: "Вход в акваторию СМП из внутренних водных путей РФ", headerButtons: {} },
    },

    {
      id: 199,
      component: "EPCSDirection",
      componentName: "EPCSDirectionMain",
      props: {
        type: "row",
      },
    },
    {
      id: 3,
      parentId: 199, 
      component: "EPCSTabs",
      componentName: "DispFloatDetailTabs",
      props: {
        event:"toggleTabs",
        dataTabs: [
          {
            name: "Сведения",
          },
          {
            name: "Маршрут",
          },
        ],
      },
    },
    {
      id: 4, 
      parentId: 3,
      component: "EPCSDirection",
      componentName: "tab1",
      col:12,
      props: {
        type: "row",
      },
    },
    {
      id: 5,
      parentId: 3,
      component: "EPCSDirection",
      componentName: "tab2",
      props: {
        type: "row",
      },
    },
    {
      id: 198,
      parentId: 4,
      component: "EPCSDirection",
      col: 8,
      componentName: "EPCSDirectionSubMain",
      props: {
        type: "row",
      },
    },
    {
      id: 101,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "name",
      props: {
        type: "selectAsync",
        placeholder: "Выберете судно",
        items: [],
        label: "1// Название судна",
        labelPosition: "top",
        value: "",
        event: "fillShip",
        labelRequired: true,
        asyncSetting: {
          displayExpr: "name",
          valueExpr: "id",
          customValue: true,
          asyncName: "Ship",
          templateRow: {
            id: null,
            name: "",
            imo: null,
          },
        },
      },
    },
    {
      id: 102,
      parentId: 198, 
      component: "EPCSFormInput",
      visible: true,
      componentName: "imo",
      props: {
        type: "selectAsync",
        placeholder: "Номер IMO",
        label: "2// Номер  IMO (при наличии)",
        labelPosition: "top",
        value: "",
        labelRequired: false,
        items: [],
        event: "fillShip",
        asyncSetting: {
          displayExpr: "imo",
          valueExpr: "id",
          customValue: true,
          asyncName: "Ship",
          templateRow: {
            id: null,
            name: "",
            imo: null,
          },
        },
      },
    },
    {
      id: 103,
      parentId: 198,
      component: "EPCSDirection",
      componentName: "EPCSDirection",
      props: {
        type: "row",
        label: "3// Порт/место отхода судна, фактические дата и время (московское) отхода ",
      },
    },
    {
      id: 104,
      parentId: 103,
      component: "EPCSFormInput",
      visible: true,
      componentName: "departureDate",
      col: 6,
      props: {
        type: "date",
      },
    },
    {
      id: 105,
      parentId: 103,
      component: "EPCSFormInput",
      visible: true,
      col: 6,
      componentName: "departurePlace",
      props: {
        placeholder: "Выберите порт/локацию",
        value: "",
        type: "selectAsync",
        items: [],
        event: "departure",
        labelRequired: true,
        asyncSetting: {
          displayExpr: "name",
          valueExpr: "name",
          customValue: true,
          asyncName: "Portplace",
          templateRow: {
            name: "",
          },
        },
      },
    },
    {
      id: 206,
      parentId: 103,
      component: "EPCSDirection",
      componentName: "EPCSdeparture",
      props: {
        type: "row",
        event: "changeCoords",
      },
    },
    {
      id: 207,
      parentId: 206,   
      component: "EPCSFormInput",
      visible: true,
      componentName: "departureLat",
      col: 4,
      props: {
        type: "number",
        step: 1,
        label: "Широта",
        labelPosition: "top",
        placeholder: "0.0",
        value: null,
      },
    },
    {
      id: 208,
      parentId: 206,
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSdepartureLat",
      col: 2,
      props: {
        type: "select",
        items: ["N", "S"],
        placeholder: "N",
        value: "N",
      },
    },
    {
      id: 209,
      parentId: 206, 
      component: "EPCSFormInput",
      visible: true,
      componentName: "departureLon",
      col: 4,
      props: {
        type: "number",
        step: 1,
        label: "Долгота",
        labelPosition: "top",
        placeholder: "0.0",
        value: null,
      },
    },
    {
      id: 210,
      parentId: 206,
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSdepartureLon",
      col: 2,
      props: {
        type: "select",
        items: ["E", "W"],
        placeholder: "E",
        value: "E",
      },
    },
    {
      id: 106,
      parentId: 198,
      component: "EPCSDirection",
      visible: true,
      componentName: "EPCStination12312Place",
      props: {
        type: "row",
        label: "4// Порт/место назначения судна, предполагаемые дата и время (московское) прибытия  ",
      },
    },
    //Добавить широту и долготу
    {
      id: 107,
      parentId: 106,  
      component: "EPCSFormInput",
      visible: true,
      componentName: "destinationDate",
      col: 6,
      props: {
        type: "date",
      },
    },
    {
      id: 108,
      parentId: 106,  
      component: "EPCSFormInput",
      visible: true,
      col: 6,
      componentName: "destinationPlace",
      props: {
        placeholder: "Выберите порт/локацию",
        value: "",
        type: "selectAsync",
        items: [],
        event: "destination",
        labelRequired: true,
        asyncSetting: {
          displayExpr: "name",
          valueExpr: "name",
          customValue: true,
          asyncName: "Portplace",
          templateRow: {
            // id: null,
            name: "",
          },
        },
      },
    },
    {
      id: 309,
      parentId: 198,
      component: "EPCSDirection",
      componentName: "EPCSdestination",
      props: {
        type: "row",
        event: "changeCoords",
      },
    },
    {
      id: 310,
      parentId: 309, 
      component: "EPCSFormInput",
      visible: true,
      componentName: "destinationLat",
      col: 4,
      props: {
        type: "number",
        step: 1,
        label: "Широта",
        labelPosition: "top",
        placeholder: "0.0",
        value: null,
      },
    },
    {
      id: 311,
      parentId: 309,
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSdestinationLat",
      col: 2,
      props: {
        type: "select",
        items: ["N", "S"],
        placeholder: "N",
        value: "N",
      },
    },
    {
      id: 312,
      parentId: 309,
      component: "EPCSFormInput",
      visible: true,
      componentName: "destinationLon",
      col: 4,
      props: {
        type: "number",
        step: 1,
        label: "Долгота",
        labelPosition: "top",
        placeholder: "0.0",
        value: null,
      },
    },
    {
      id: 313,
      parentId: 309, 
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSdestinationLon",
      col: 2,
      props: {
        type: "select",
        items: ["E", "W"],
        placeholder: "E",
        value: "E",
      },
    },
    {
      id: 109,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      col: 8,
      componentName: "draught",
      props: {
        type: "number",
        step: 1,
        label: "5// Максимальная действующая осадка судна, м",
        labelPosition: "left",
        placeholder: "0.0",
      },
    },
    {
      id: 909,
      parentId: 5,
      component: "EPCSDirection",
      componentName: "routeLeftSide",
      col: 5,
      props: {
        type: "row",
      },
    },

    {
      id: 901,
      parentId: 909,
      component: "EPCSDirection",
      componentName: "routeLabel",
      col: 10,
      props: {
        label: `Введите координаты точек предполагаемого маршрута плавания в поля ввода координат или нарисуйте маршрут на карте`,
      },
    },

    {
      id: 902,
      parentId: 909,
      componentName: "activateRouteMapButton",
      component: "EPCSButtonTittleBar",
      col: 1,
      props: {
        event: "activateRouteMap",
        iconData: "F08F",
        isPressed: false,
      },
    },

    {
      id: 903,
      parentId: 909,
      componentName: "clearRouteButton",
      component: "EPCSButtonTittleBar",
      col: 1,
      props: {
        event: "clearRoute",
        iconData: "F06C",
        isPressed: false,
      },
    },
    {
      id: 904,
      parentId: 909,
      component: "EPCSDirection",
      componentName: "route",
      col: 12,
      props: {
        type: "row",
        event: "coordinatesChange",
      },
    },
    {
      id: 905,
      parentId: 5,
      component: "EPCSMap",
      componentName: "routeMap",
      name: "routeMap",
      col: 7,
      props: {
        mapId: "routeMap",
        event: "mapCoordinatesChange",
      },
    },
    {
      id: 200,
      priority: 5,
      component: "EPCSFooter",
      visible: true,
      componentName: "EPCSFooter",
      props: {
        leftEvent: "checkSave",
        leftType: "primary",
        leftLabel: "Назад",
        rightLabel: "Отправить",
        rightType: "primary",
        rightEvent: "saveDisp",
      },
    },
    {
      id: 202,
       
      parentId: 0,
      visible: true,
      component: "EPCSPopup",
      componentName: "EPCSPopup",
    },
  ],
};
