export default {
  structureType: "Form",
  components: [
    {
      id: 100,
      priority: 1,
      parentId: 0,
      visible: true,
      componentName: "CreateDispAquaHeader",
      component: "EPCSFormHeader",
      props: { title: "Плавание в акватории СМП", headerButtons: {} },
    },
    {
      id: 199,
      priority: 1,
      component: "EPCSDirection",
      componentName: "EPCSDirectionMain",
      props: {
        type: "row",
      },
    },
    {
      id: 3,
      parentId: 199,
      priority: 1,
      component: "EPCSTabs",
      componentName: "DispFloatDetailTabs",
      props: {
        dataTabs: [
          {
            name: "Сведения",
          },
          {
            name: "Маршрут",
          },
        ],
      },
    },
    {
      id: 4,
      priority: 1,
      parentId: 3,
      component: "EPCSDirection",
      componentName: "tab1",
      col:12,
      props: {
        type: "row",
      },
    },
    {
      id: 5,
      priority: 1,
      parentId: 3,
      component: "EPCSDirection",
      componentName: "tab2",
      props: {
        type: "row",
      },
    },
    {
      id: 198,
      parentId: 4,
      priority: 1,
      component: "EPCSDirection",
      componentName: "EPCSDirectionSubMain",
      col: 6,
      props: {
        type: "row",
      },
    },
    {
      id: 101,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "name",
      props: {
        type: "selectAsync",
        placeholder: "Выберете судно",
        items: [],
        label: "1\/\/ Название судна",
        labelPosition: "top",
        value: "",
        event: "fillShip",
        labelRequired: true,
        asyncSetting: {
          displayExpr: "name",
          valueExpr: "id",
          customValue: true,
          asyncName: "Ship",
          templateRow: {
            id: null,
            name: "",
            imo: null,
          },
        },
      },
    },
    {
      id: 102,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "imo",
      props: {
        type: "selectAsync",
        placeholder: "Номер IMO",
        label: "2\/\/ Номер  IMO (при наличии)",
        labelPosition: "top",
        value: "",
        labelRequired: false,
        items: [],
        event: "fillShip",
        // pattern:"^(.{7})$",
        invalidMessage:"IMO должно состоять из 7 символов",

        asyncSetting: {
          displayExpr: "imo",
          valueExpr: "id",
          customValue: true,
          asyncName: "Ship",
          templateRow: {
            id: null,
            name: "",
            imo: null,
          },
        },
      },
    },

    {
      id: 103,
      parentId: 198,
      priority: 1,
      component: "EPCSDirection",
      componentName: "EPCSCoordsShip",
      props: {
        type: "row",
        event: "changeCoords",
        label: "3// Географические координаты судна (с точностью до десятых долей минуты)",
      },
    },
    {
      id: 104,
      parentId: 103,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "placeNsrLat",
      col: 3,
      props: {
        type: "number",
        step: 1,
        label: "Широта",
        labelPosition: "top",
        // value: "",
        placeholder: "0.0",
      },
    },
    {
      id: 105,
      parentId: 103,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSplaceNsrLat",
      col: 3,
      props: {
        type: "select",
        items: ["N", "S"],
        placeholder: "N",
        value: "N",
      },
    },
    {
      id: 106,
      parentId: 103,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "placeNsrLon",
      col: 3,
      props: {
        type: "number",
        step: 1,
        label: "Долгота",
        labelPosition: "top",
        placeholder: "0.0",
        // value: "",
      },
    },
    {
      id: 107,
      parentId: 103,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSplaceNsrLon",
      col: 3,
      props: {
        type: "select",
        items: ["E", "W"],
        placeholder: "E",
        value: "E",
      },
    },
    // {
    //   id: 108,
    //   parentId: 103,
    //   priority: 1,
    //   component: "EPCSButtonTittleBar",
    //   visible: true,
    //   componentName: "EPCSTEST141d2312422",
    //   col: 1,
    //   props: {
    //     iconData: "F056",
    //     isPressed: false,
    //     event: "addMarker",
    //     label: "",
    //     type: "small",
    //     disabled: false,
    //     name: "EPCSDirectionCoordinates",
    //   },
    // },
    {
      id: 108,
      parentId: 198,
      priority: 1,
      component: "EPCSDirection",
      visible: true,
      componentName: "EPCSDirection12",
      props: {
        type: "row",
        label: `4\/\/ Планируемые дата и время (московское) выхода судна из акватории СМП или
         планируемое время прихода судна в морской порт акватории СМП или название места/пункта работ`,
      },
    },
    {
      id: 109,
      parentId: 108,
      priority: 1,
      component: "EPCSRadioButtonGroup",
      visible: true,
      componentName: "exitType",
      col: 12,
      props: {
        inputData: {
          1: "Следование в акваторию СМП",
          2: "Вход в акваторию СМП",
        },
        value: 1,
      },
    },
    {
      id: 110,
      priority: 1,
      parentId: 108,
      component: "EPCSFormInput",
      visible: true,
      componentName: "exitDate",
      col: 6,
      props: {
        type: "date",
        value: "",
      },
    },
    {
      id: 111,
      priority: 1,
      parentId: 108,
      component: "EPCSFormInput",
      visible: true,
      componentName: "exitPlace",
      col: 6,
      props: {
        type: "text",
        placeholder: "Выберите порт/локацию",
        value: "",
      },
    },
    {
      id: 218,
      parentId: 198,
      priority: 1,
      component: "EPCSDirection",
      componentName: "EPCSExit",
      props: {
        type: "row",
        event: "changeCoords",
      },
    },
    {
      id: 219,
      parentId: 218,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "exitLat",
      col: 3,
      props: {
        type: "number",
        step: 1,
        label: "Широта",
        labelPosition: "top",
        // value: "",
        placeholder: "0.0",
      },
    },
    {
      id: 220,
      parentId: 218,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSexitLat",
      col: 2,
      props: {
        type: "select",
        items: ["N", "S"],
        placeholder: "N",
        value: "N",
      },
    },
    {
      id: 221,
      parentId: 218,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "exitLon",
      col: 3,
      props: {
        type: "number",
        step: 1,
        label: "Долгота",
        labelPosition: "top",
        placeholder: "0.0",
        // value: "",
      },
    },
    {
      id: 222,
      parentId: 218,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSexitLon",
      col: 2,
      props: {
        type: "select",
        items: ["E", "W"],
        placeholder: "E",
        value: "E",
      },
    },
    {
      id: 223,
      parentId: 218,
      priority: 1,
      component: "EPCSButtonTittleBar",
      visible: true,
      componentName: "EPCSBTNexit",
      col: 1,
      props: {
        iconData: "F056",
        isPressed: false,
        event: "addMarker",
        label: "",
        type: "small",
        disabled: false,
        name: "EPCSExit",
      },
    },
    {
      id: 112,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "course",
      props: {
        type: "number",
        step: 1,
        label: "5// Курс судна с точностью до 1 градуса",
        labelPosition: "left",
        // value: "",
        placeholder: "000",
      },
    },
    {
      id: 113,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "speed",
      props: {
        type: "number",
        step: 1,
        label: "6// Скорость судна с точностью до 1 узла",
        labelPosition: "left",
        placeholder: "0.0",
        // value: "",
      },
    },
    {
      id: 114,
      parentId: 198,
      priority: 1,
      component: "EPCSDirection",
      visible: true,
      componentName: "direc1as22sadf323a",
      props: {
        type: "row",
        label: "7// Количество топлива на борту судна в метрических тоннах",
      },
    },
    {
      id: 116,
      parentId: 114,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "fuelHeavy",
      col: 6,
      props: {
        type: "number",
        step: 1,
        placeholder: "0.0",
        // label: "Выберите тип топлива",
        label: "Тяжелое",
        labelPosition: "left",
      },
    },
    {
      id: 216,
      parentId: 114,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "fuelLight",
      col: 6,
      props: {
        type: "number",
        step: 1,
        placeholder: "0.0",
        // label: "Выберите тип топлива",
        label: "Легкое",
        labelPosition: "left",
      },
    },
    {
      id: 226,
      parentId: 114,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "fuelSpg",
      col: 6,
      props: {
        type: "number",
        step: 1,
        placeholder: "0.0",
        // label: "Выберите тип топлива",
        label: "Топливо СПГ",
        labelPosition: "left",
      },
    },
    {
      id: 115,
      parentId: 114,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "fuelDays",
      col: 6,
      props: {
        type: "number",
        step: 1,
        placeholder: "0.0",
        // label: "Выберите тип топлива",
        label: "Сутки",
        labelPosition: "left",
      },
    },
    {
      id: 118,
      priority: 1,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "water",
      props: {
        type: "number",
        step: 1,
        label: "8// Количество пресной воды в метрических тоннах",
        labelPosition: "left",
        // value: "",
        placeholder: "000",
      },
    },
    {
      id: 119,
      priority: 1,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "incidents",
      props: {
        type: "select",
        value: "НЕТ",
        items: ["НЕТ", "ДА"],
        label: `9\/\/ Сведения о происшествиях с членом экипажа судна или пассажиром (при наличии)
           о повреждениях корпуса, неисправностях судовых машин, механизмов и (или) технических средств (при наличии)`,
        labelPosition: "top",

        placeholder: "000",
      },
    },
    {
      id: 120,
      priority: 1,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "shipFault",
      props: {
        type: "select",
        value: "НЕТ",
        items: ["НЕТ", "ДА"],
        label: `10\/\/ Сведения о повреждениях корпуса, неисправностях судовых машин, механизмов и (или) технических средств (при наличии)`,
        labelPosition: "top",

        placeholder: "000",
      },
    },
    {
      id: 121,
      priority: 1,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "emergency", //??? точно ли? и предыдущие 2
      props: {
        type: "select",
        value: "НЕТ",
        items: ["НЕТ", "ДА"],
        label: `11\/\/ Иные сведения, относящиеся к безопасности мореплавания и защите морской среды от загрязнения с судов (при наличии)`,
        labelPosition: "top",
        placeholder: "000",
      },
    },
    {
      id: 122,
      priority: 1,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "atmTemperature",
      props: {
        type: "number",
        step: 1,
        label: "12// Температура воздуха с точностью до 1 градуса, °С",
        labelPosition: "left",
        // value: "",
        placeholder: "000",
      },
    },
    {
      id: 123,
      priority: 1,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "atmPressure",
      props: {
        type: "number",
        step: 1,
        label: "13//Атмосферное давление в миллибарах",
        labelPosition: "left",
        // value: "",
        placeholder: "000",
      },
    },
    {
      id: 124,
      parentId: 198,
      priority: 1,
      component: "EPCSDirection",
      visible: true,
      componentName: "dir13a",
      props: {
        type: "row",
        label: "14// Направление и скорость ветра с точностью до 10 градусов и одного метра в секунду",
      },
    },
    {
      id: 125,
      parentId: 124,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "windDir",
      col: 6,
      props: {
        type: "number",
        step: 1,
        items: [1, 2],
        placeholder: "000",
        label: "Направление",
        labelPosition: "left",
      },
    },
    {
      id: 126,
      parentId: 124,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "windSpeed",
      col: 6,
      props: {
        type: "number",
        step: 1,
        placeholder: "0",
        label: "Скорость",
        labelPosition: "left",
      },
    },
    {
      id: 127,
      priority: 1,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "visibility",
      props: {
        type: "number",
        step: 1,
        label: "15// Видимость в морских милях с точностью до 1 мили",
        labelPosition: "left",
        // value: "",
        placeholder: "000",
      },
    },
    {
      id: 128,
      priority: 1,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "weatherEvents",
      props: {
        type: "text",
        label: "16// Явления погоды в срок наблюдения (туман, дымка, дождь, снег и пр.)",
        labelPosition: "top",
        value: "",
        placeholder: "Укажите погодные явления",
      },
    },
    {
      id: 129,
      priority: 1,
      parentId: 198,
      component: "EPCSFormInput",
      visible: true,
      componentName: "waterTemperature",
      props: {
        type: "number",
        step: 1,
        label: "17// Температура забортной воды с точностью до 1 градуса, °С",
        labelPosition: "left",
        value: 0,
        placeholder: "0",
      },
    },
    {
      id: 130,
      parentId: 198,
      priority: 1,
      component: "EPCSAccordion",
      visible: true,
      componentName: "EPCSacc12122",
      props: {
        typeAddBtn: "outline",
        addLabel: "Добавить данные объекта",
        typeRemoveBtn: "primary",
        removeLabel: "Удалить данные объекта",
      },
    },
    {
      id: 131,
      parentId: 130,
      priority: 1,
      component: "EPCSDirection",
      visible: true,
      componentName: "EPCSaadirec1as22sadf323a",
      props: {
        type: "row",
        label: `18\/\/ Наличие айсбергов, обломков и кусков айсбергов, в котором указываются 
        время (московское) и дата обнаружения/ их координаты/ ориентировочные линейные
        размеры (ширина-высота)/ скорость и направление ветра`,
      },
    },
    {
      id: 132,
      parentId: 131,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "yo21243",
      props: {
        type: "date",
        placeholder: "0.0",
        label: "Время и дата обнаружения",
        labelPosition: "left",
      },
    },
    {
      id: 133,
      parentId: 131,
      priority: 1,
      component: "EPCSDirection",
      componentName: "EPCSDirectionIce",
      props: {
        type: "row",
        event: "changeCoords",
        label: "Географические координаты айсберга",
      },
    },
    {
      id: 134,
      parentId: 133,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "placeNsrLa1t",
      col: 3,
      props: {
        type: "number",
        step: 1,
        label: "Широта",
        labelPosition: "top",
        // value: "",
        placeholder: "0.0",
      },
    },
    {
      id: 135,
      parentId: 133,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSplaceNsrLa1t",
      col: 2,
      props: {
        type: "select",
        items: ["N", "S"],
        placeholder: "N",
        value: "N",
      },
    },
    {
      id: 136,
      parentId: 133,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "placeNsrLo1n",
      col: 3,
      props: {
        type: "number",
        step: 1,
        label: "Долгота",
        labelPosition: "top",
        placeholder: "0.0",
        // value: "",
      },
    },
    {
      id: 137,
      parentId: 133,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "EPCSplaceNsrLo1n",
      col: 2,
      props: {
        type: "select",
        items: ["E", "W"],
        placeholder: "E",
        value: "E",
      },
    },
    {
      id: 208,
      parentId: 133,
      priority: 1,
      component: "EPCSButtonTittleBar",
      visible: true,
      componentName: "EPCSTEST141d23124122",
      col: 1,
      props: {
        iconData: "F056",
        isPressed: false,
        event: "addMarker",
        label: "",
        type: "small",
        disabled: false,
        name: "EPCSDirectionIce",
      },
    },
    {
      id: 209,
      parentId: 131,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "xx",
      col: 6,
      props: {
        type: "number",
        step: 1,
        label: "Ширина, м",
        labelPosition: "left",
        // value: "",
        placeholder: "0",
      },
    },
    {
      id: 210,
      parentId: 131,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "xxz",
      col: 6,
      props: {
        type: "number",
        step: 1,
        label: "Высота, м",
        labelPosition: "left",
        // value: "",
        placeholder: "0",
      },
    },
    {
      id: 211,
      parentId: 131,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "xxz1",
      props: {
        type: "number",
        step: 1,
        label: "Скорость ветра",
        labelPosition: "left",
        // value: "",
        placeholder: "0",
      },
    },
    {
      id: 212,
      parentId: 131,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "xxz21",
      props: {
        type: "number",
        step: 1,
        label: "Направление ветра",
        labelPosition: "left",
        // value: "",
        placeholder: "000",
      },
    },
    {
      id: 138,
      parentId: 198,
      priority: 1,
      component: "EPCSDirection",
      visible: true,
      componentName: "EPCSDirection122",
      props: {
        type: "row",
        label: `19\/\/ Общая сплоченность льда по десятибалльной
         шкале, возраст льда с указанием частной сплоченности, для припайного льда указывается кодовое слово ПРИПАЙ`,
      },
    },
    {
      id: 139,
      parentId: 138,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "ct",
      props: {
        type: "text",
        label: "Общая сплоченность льда",
        labelPosition: "left",
        value: "",
        placeholder: "Выберите общую сплоченность",
      },
    },
    {
      id: 140,
      parentId: 198,
      priority: 1,
      component: "EPCSDirection",
      visible: true,
      componentName: "EPCSDirection121232",
      props: {
        type: "row",
        label: `Наиболее старый лед`,
      },
    },
    {
      id: 141,
      parentId: 140,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "sa", //???
      col: 6,
      props: {
        type: "number",
        step: 1,
        label: "Возраст",
        labelPosition: "left",
        // value: "",
        placeholder: "Выберите возраст",
      },
    },
    {
      id: 142,
      parentId: 140,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "ca", //???
      col: 6,
      props: {
        type: "text",
        label: "Сплоченность",
        labelPosition: "left",
        value: "",
        placeholder: "Сплоченность",
      },
    },
    {
      id: 143,
      parentId: 198,
      priority: 1,
      component: "EPCSDirection",
      visible: true,
      componentName: "EPCSDIR123",
      props: {
        type: "row",
        label: `Менее старый лед`,
      },
    },
    {
      id: 144,
      parentId: 143,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "sb", //???
      col: 6,
      props: {
        type: "number",
        step: 1,
        label: "Возраст",
        labelPosition: "left",
        // value: "",
        placeholder: "Выберите возраст",
      },
    },

    {
      id: 145,
      parentId: 143,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "cb", //???
      col: 6,
      props: {
        type: "text",
        label: "Сплоченность",
        labelPosition: "left",
        value: "",
        placeholder: "Сплоченность",
      },
    },
    {
      id: 146,
      parentId: 198,
      priority: 1,
      component: "EPCSDirection",
      visible: true,
      componentName: "EPCSDirecsdwnwe121232",
      props: {
        type: "row",
        label: `Наиболее молодой лед`,
      },
    },
    {
      id: 147,
      parentId: 146,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "sc", //???
      col: 6,
      props: {
        type: "number",
        step: 1,
        label: "Возраст",
        labelPosition: "left",
        // value: "",
        placeholder: "Выберите возраст",
      },
    },

    {
      id: 148,
      parentId: 146,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "cc", //???
      col: 6,
      props: {
        type: "text",
        label: "Сплоченность",
        labelPosition: "left",
        value: "",
        placeholder: "Сплоченность",
      },
    },
    {
      id: 149,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "iceCompression", //???
      props: {
        type: "number",
        step: 1,
        label: "20// Сжатие льдов в баллах по трехбалльной шкале в соответствии с номенклатурой морских льдов",
        labelPosition: "top",
        // value: "",
        placeholder: "Выберите сжатие",
      },
    },
    {
      id: 150,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "iceRidge", //???
      props: {
        type: "number",
        step: 1,
        label: "21// Торосистость льда в баллах по пятибалльной шкале в соответствии с номенклатурой морских льдов",
        labelPosition: "top",
        // value: "",
        placeholder: "Выберите торосистость",
      },
    },
    {
      id: 151,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "iceDestruction", //???
      props: {
        type: "number",
        step: 1,
        label: "22// Разрушенность льда в баллах по пятибалльной шкале в соответствии с номенклатурой морских льдов",
        labelPosition: "top",
        // value: "",
        placeholder: "Выберите разрушенность",
      },
    },
    {
      id: 152,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "icing", //???
      props: {
        type: "select",
        label: "23// Наличие обледенения судна",
        labelPosition: "left",
        value: "НЕТ",
        items: ["НЕТ", "ДА"],
        placeholder: "",
      },
    },
    {
      id: 153,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "iceEvents", //???
      props: {
        type: "text",
        label: "24// Ледовые явления как интенсивный дрейф, ледовая река",
        labelPosition: "top",
        value: "",
        placeholder: "Укажите ледовые явления",
      },
    },
    {
      id: 154,
      parentId: 198,
      priority: 1,
      component: "EPCSFormInput",
      visible: true,
      componentName: "equipmentFault", //???
      props: {
        type: "text",
        label: `25\/\/ Обнаружение неисправности или отсутствия 
        средств навигационного оборудования, указанного на навигационной карте или в навигационном пособии`,
        labelPosition: "top",
        value: "НЕТ",
        items: ["НЕТ", "ДА"],
        placeholder: "",
      },
    },
    
    {
      id: 201,
      parentId: 4,
      priority: 1,
      component: "EPCSMap",
      visible: true,
      col: 6,
      componentName: "EPCSSwimDispAquaMap",
      name: "SwimDispAquaMap",
      props: { mapId: "SwimDispAquaMap" },
    },
    {
      id: 309,
      parentId: 5,
      priority: 1,
      component: "EPCSDirection",
      componentName: "routeLeftSide",
      col: 5,
      props: {
        type: "row",
      },
    },

    {
      id: 901,
      parentId: 309,
      priority: 1,
      component: "EPCSDirection",
      componentName: "routeLabel",
      col: 10,
      props: {
        label: `Введите координаты точек предполагаемого маршрута плавания в поля ввода координат или нарисуйте маршрут на карте`,
      },
    },

    {
      id: 902,
      priority: 1,
      parentId: 309,
      componentName: "activateRouteMapButton",
      component: "EPCSButtonTittleBar",
      col: 1,
      props: {
        event: "activateRouteMap",
        iconData: "F08F",
        isPressed: false,
      },
    },

    {
      id: 903,
      priority: 1,
      parentId: 309,
      componentName: "clearRouteButton",
      component: "EPCSButtonTittleBar",
      col: 1,
      props: {
        event: "clearRoute",
        iconData: "F06C",
        isPressed: false,
      },
    },

    {
      id: 904,
      parentId: 309,
      priority: 1,
      component: "EPCSDirection",
      componentName: "route",
      col: 12,
      props: {
        type: "row",
        event: "coordinatesChange",
      },
    },
    {
      id: 905,
      parentId: 5,
      priority: 1,
      component: "EPCSMap",
      componentName: "routeMap",
      name: "routeMap",
      col: 7,
      props: {
        mapId: "routeMap",
        event: "mapCoordinatesChange",
      }
    },

    {
      id: 200,
      priority: 5,
      component: "EPCSFooter",
      visible: true,
      componentName: "EPCSFooter",
      props: {
        leftEvent: "checkSave",
        leftType: "primary",
        leftLabel: "Назад",
        rightLabel: "Отправить",
        rightType: "primary",
        rightEvent: "saveDisp",
      },
    },
    {
      id: 202,
      priority: 1,
      parentId: 0,
      visible: true,
      component: "EPCSPopup",
      componentName: "EPCSPopup",
    },
  ],
};
